name: Git Actions Demo
on: [push]
jobs:
 Explore-GitHub-Actions:
   runs-on: macos-latest
   steps:
     - uses: actions/checkout@v2
     - run: echo "The job was automatically triggered by a ${{ github.event_name }} event"
     - run: python Test_1.py